/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ConsultIndexRouteImport } from './routes/consult.index'
import { Route as ConsultCompleteRouteImport } from './routes/consult.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConsultIndexRoute = ConsultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultRoute,
} as any)
const ConsultCompleteRoute = ConsultCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ConsultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consult': typeof ConsultRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/consult/complete': typeof ConsultCompleteRoute
  '/consult/': typeof ConsultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/consult/complete': typeof ConsultCompleteRoute
  '/consult': typeof ConsultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/consult': typeof ConsultRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/consult/complete': typeof ConsultCompleteRoute
  '/consult/': typeof ConsultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/consult' | '/admin' | '/consult/complete' | '/consult/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin' | '/consult/complete' | '/consult'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/consult'
    | '/_authenticated/admin'
    | '/consult/complete'
    | '/consult/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsultRoute: typeof ConsultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/consult/': {
      id: '/consult/'
      path: '/'
      fullPath: '/consult/'
      preLoaderRoute: typeof ConsultIndexRouteImport
      parentRoute: typeof ConsultRoute
    }
    '/consult/complete': {
      id: '/consult/complete'
      path: '/complete'
      fullPath: '/consult/complete'
      preLoaderRoute: typeof ConsultCompleteRouteImport
      parentRoute: typeof ConsultRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConsultRouteChildren {
  ConsultCompleteRoute: typeof ConsultCompleteRoute
  ConsultIndexRoute: typeof ConsultIndexRoute
}

const ConsultRouteChildren: ConsultRouteChildren = {
  ConsultCompleteRoute: ConsultCompleteRoute,
  ConsultIndexRoute: ConsultIndexRoute,
}

const ConsultRouteWithChildren =
  ConsultRoute._addFileChildren(ConsultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsultRoute: ConsultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
